version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build_and_test:
    working_directory: ~/markets-etl
    docker:
    - image: circleci/clojure:lein-2.9.0
    - image: circleci/postgres:9.6.9-alpine # for integration test
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - setup_remote_docker
      - run: (lein cloverage --codecov & 2>/dev/null; lein test & 2>/dev/null; lein cljfmt check & 2>/dev/null) && wait && deploy/bin/publish-image
      - codecov/upload:
          file: target/coverage/codecov.json
      - store_artifacts:
          path: target/uberjar/app.jar

workflows:
  version: 2
  commit:
    jobs:
      - build_and_test
