version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  clojure_and_postgres:
    working_directory: ~/markets-etl
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin:/root/.local/bin
      - TEST_JDBC_DB_URI: jdbc:postgresql://localhost:5432/postgres?loginTimeout=30&socketTimeout=900&tcpKeepAlive=true&user=postgres
    docker:
      - image: circleci/clojure:lein-2.9.0    # leave this pinned; using cimg/clojure:1.10.1 fails
      - image: circleci/postgres:9.6.9-alpine # for integration test
  clojure:
    working_directory: ~/markets-etl
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin:/root/.local/bin
    docker:
      - image: circleci/clojure:lein-2.9.0    # leave this pinned; using cimg/clojure:1.10.1 fails

commands:
  restore_and_save_cache:
    steps:
      - restore_cache:
          key: \<< checksum "project.clj" \>> # << and >> must be escaped: https://circleci.com/docs/2.0/build-processing/#limitations
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: \<< checksum "project.clj" \>>
  install_aws_cli:
    steps:
      - run: sudo apt update; sudo apt install -y -qq python3-pip; pip3 install awscli --upgrade --user

jobs:
  test:
    executor: clojure_and_postgres
    steps:
      - checkout
      - restore_and_save_cache
      - run: lein cloverage --codecov
      - run: lein test
      - run: lein cljfmt check
      - codecov/upload:
          file: target/coverage/codecov.json
  publish:
    executor: clojure
    steps:
      - checkout
      - restore_and_save_cache
      - setup_remote_docker
      - run: deploy/bin/publish-image
      - store_artifacts:
          path: target/uberjar/app.jar
  markets-etl-lambda-build-and-deploy:
    executor: clojure
    steps:
      - install_aws_cli
      - run: git clone https://github.com/skilbjo/lambdas.git ~/lambdas
      - run: git clone https://github.com/skilbjo/markets-etl.git ~/markets-etl
      - run: cd ~/lambdas; cd markets-etl; deploy/build-project
      - run: cd ~/lambdas; cd markets-etl; lein uberjar
      - run: mkdir -p ~/.aws; echo '[skilbjo-robot]' >~/.aws/credentials; echo "aws_access_key_id = $robot_aws_access_key_id" >>~/.aws/credentials; echo "aws_secret_access_key = $robot_aws_secret_access_key" >>~/.aws/credentials;
      - run: if [[ $CIRCLE_BRANCH == 'master' ]]; then cd markets-etl; deploy/publish-lambda; fi    # uncomment to turn on auto-deploys

workflows:
  commit:
    jobs:
      #- test
      #- publish:
          #requires:
          #- test
      - markets-etl-lambda-build-and-deploy:
          filters:
            branches:
              only:
                - master
          #requires:
            #- test
