version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  clojure_and_postgres:
    working_directory: ~/markets-etl
    environment:
      - PATH: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/circleci/.local/bin:/root/.local/bin
      - TEST_JDBC_DB_URI: jdbc:postgresql://localhost:5432/postgres?loginTimeout=30&socketTimeout=900&tcpKeepAlive=true&user=postgres
    docker:
      - image: circleci/clojure:lein-2.9.0
      - image: circleci/postgres:9.6.9-alpine # for integration test

commands:
  restore_and_save_cache:
    steps:
      - restore_cache:
          key: \<< checksum "project.clj" \>> # << and >> must be escaped: https://circleci.com/docs/2.0/build-processing/#limitations
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: \<< checksum "project.clj" \>>

jobs:
  test-and-publish:
    executor: clojure_and_postgres
    steps:
      - checkout
      - restore_and_save_cache
      - setup_remote_docker
      - run: (lein cloverage --codecov & 2>/dev/null; lein test & 2>/dev/null; lein cljfmt check & 2>/dev/null) && wait && deploy/bin/publish-image
      - codecov/upload:
          file: target/coverage/codecov.json
      - store_artifacts:
          path: target/uberjar/app.jar

workflows:
  commit:
    jobs:
      - test-and-publish
